# NumPy Exercises

#### Import NumPy as np

In [11]:
import numpy as np

#### Create an array of 10 zeros 

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [57]:
arr1 = np.full((10),5)
arr1


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [51]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [49]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [59]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [65]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [33]:
arr = np.array(np.random.rand())
arr

array(0.4781832)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [35]:
arr = np.array(np.random.rand(25))
arr

array([0.32717039, 0.37745588, 0.60789897, 0.47427621, 0.79421934,
       0.82720266, 0.54897393, 0.1663687 , 0.27733694, 0.49617665,
       0.1546231 , 0.71091129, 0.23711158, 0.71878412, 0.85519352,
       0.69764669, 0.79376277, 0.39819663, 0.61510147, 0.04214649,
       0.08675687, 0.63280082, 0.53450766, 0.49720969, 0.18810209])

#### Create the following matrix:

In [45]:
arr = np.array(np.random.rand(50)).reshape(5,10)
arr

array([[0.98178021, 0.43856521, 0.25282229, 0.50519831, 0.43311238,
        0.52289857, 0.19074215, 0.26912646, 0.64318181, 0.90141663],
       [0.12704867, 0.98382123, 0.68555699, 0.68512669, 0.03321742,
        0.51934091, 0.75520139, 0.12466936, 0.15493473, 0.39456226],
       [0.27256542, 0.48899619, 0.03266837, 0.02612559, 0.44972141,
        0.14455615, 0.64991759, 0.4340354 , 0.8195651 , 0.46672507],
       [0.24630419, 0.95845358, 0.81075394, 0.21009613, 0.02753208,
        0.33705432, 0.2767799 , 0.66183964, 0.83343647, 0.68791848],
       [0.03648735, 0.25732838, 0.65872899, 0.6272172 , 0.66320378,
        0.46410071, 0.49097477, 0.79474596, 0.37962171, 0.6518968 ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [47]:
arr = np.array(np.linspace(0,1,num=20)).reshape(4,5)
arr

array([[0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632],
       [0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421],
       [0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211],
       [0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ]])

#### Numpy Indexing and Selection, write code that reproduces the output of the cell below

In [49]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
mat[2::,1::]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [56]:
mat[0:3,[1]]

array([[ 2],
       [ 7],
       [12]])

In [58]:
mat[-1]

array([21, 22, 23, 24, 25])

In [72]:
mat[[-2,-1],::]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [76]:
 x = mat.sum()
 x

325

#### Get the standard deviation of the values in mat

In [80]:
st = mat.std()
st

7.211102550927978

#### Get the sum of all the columns in mat

In [84]:
re = np.array(np.sum(mat,axis=0))
re

array([55, 60, 65, 70, 75])

==========

# Great Job!